version: '3.8'

services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_volume:/home/pro/web/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/pro/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./config/.env.prod
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./DB:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: "movies_database"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
